default[:monit][:check_interval] = 120
default[:monit][:log] = '/var/log/monit.log'
default[:monit][:mailserver][:host] = 'localhost'
default[:monit][:mailserver][:port] = 25
default[:monit][:httpd][:enable] = false
default[:monit][:httpd][:port] = 2812
default[:monit][:httpd][:user] = 'admin'
default[:monit][:httpd][:password] = 'monit' # TODO move it to data bag
default[:monit][:mailformat][:from] = "root@#{node[:fqdn]}"
default[:monit][:mailformat][:subject] = 'monit alert --  $EVENT $SERVICE'
default[:monit][:mmonit_url] = nil
